### ISSUE TITLE
In Learning example predicted probability for every candidate is always 0.5

### ISSUE THREAD

**Issue by Jerrycjw** [HazyResearch/ddlite#186]
Hi everyone,

In example GeneTaggerExample_Learning, after running the example code, I try to get the predicted probability for each candidate, but it is always 0.5 no matter what subset I choose. Is there anything I need to watch out when I use the function get_predicated_probability?

Thank you.

**Comment by henryre** [comment]
Hi,
Depending on your settings for the learning function, this can be expected behavior for that example. Since the labeling functions cover a small fraction of the candidates, the signal they provide can get "regularized out". This is only meant to be an example of the workflow for DDLite, not an example of a working application. We're working on getting some more complete examples posted, but we'll keep this question open in Issues until we do!
