### ISSUE TITLE
Add MindTagger evaluation utilities

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#43]
Should we focus on the hold out set? What are the important metrics to users wanting to refine their DSRs?

**Comment by jason-fries** [comment]
I think this is pretty important -- I'm finishing a (pretty rough) Corpus class in dd-biolib so that we can load some benchmark datasets for the entity bio-hackathon. It would be great to see some nicer feedback than just P/R/F1 on the dev set, though I'm not certain what that feedback should look like.
