### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by henryre** [HazyResearch/ddlite#56]
Example notebooks are the de facto documentation. Example notebooks are not actually documentation.

**Comment by ajratner** [comment]
There's some stuff I wrote on the README before... although don't know if that passes for "documentation" in the proper sense either :)?  Regardless we should consolidate so that we don't have redundant stale copies floating around- maybe light documentation in the README with reference to the notebooks for examples?

**Comment by henryre** [comment]
Yeah that's what I was thinking
